/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/ingredient/": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": {
              data?: {
                  /** Format: int64 */
                  creation_date: number;
                  /** Format: int64 */
                  id: number;
                  name: string;
                }[] | null;
              message: string;
            };
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": {
            name: string;
          };
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              data?: {
                /** Format: int64 */
                creation_date: number;
                /** Format: int64 */
                id: number;
                name: string;
              } | null;
              message: string;
            };
          };
        };
      };
    };
  };
  "/ingredient/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              data?: {
                /** Format: int64 */
                creation_date: number;
                /** Format: int64 */
                id: number;
                name: string;
              } | null;
              message: string;
            };
          };
        };
      };
    };
  };
  "/dish/": {
    get: {
      parameters: {
        query?: {
          is_finished?: boolean | null;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              data?: (({
                  /** Format: int64 */
                  creation_date: number;
                  /** Format: int64 */
                  id: number;
                  is_finished: boolean;
                  name?: string | null;
                  /** Format: int64 */
                  prep_date?: number | null;
                })[]) | null;
              message: string;
            };
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": {
            dish_ingredients?: {
                /** Format: int64 */
                ingredient_id: number;
                /** Format: int64 */
                weight: number;
              }[] | null;
            name: string;
            /** Format: int64 */
            prep_date?: number | null;
            /** Format: int64 */
            total_weight?: number | null;
          };
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              data?: ([{
                  /** Format: int64 */
                  creation_date: number;
                  /** Format: int64 */
                  id: number;
                  /** Format: int64 */
                  is_finished: number;
                  name?: string | null;
                  /** Format: int64 */
                  prep_date?: number | null;
                  /** Format: int64 */
                  total_weight: number;
                }, {
                    /** Format: int64 */
                    creation_date: number;
                    /** Format: int64 */
                    dish_id: number;
                    /** Format: int64 */
                    ingredient_id: number;
                    /** Format: int64 */
                    weight: number;
                  }[]]) | null;
              message: string;
            };
          };
        };
      };
    };
  };
  "/dish/{dish_id}/": {
    get: {
      parameters: {
        path: {
          dish_id: number;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              data?: ({
                added_ingredients: {
                    /** Format: int64 */
                    addition_date: number;
                    /** Format: int64 */
                    ingredient_id: number;
                    ingredient_name: string;
                    /** Format: int64 */
                    weight: number;
                  }[];
                dish: {
                  /** Format: int64 */
                  creation_date: number;
                  /** Format: int64 */
                  id: number;
                  /** Format: int64 */
                  is_finished: number;
                  name?: string | null;
                  /** Format: int64 */
                  prep_date?: number | null;
                  /** Format: int64 */
                  total_weight: number;
                };
                used_at: ({
                    /** Format: int64 */
                    eat_date?: number | null;
                    meal_description?: string | null;
                    /** Format: int64 */
                    meal_id: number;
                    /** Format: int64 */
                    weight?: number | null;
                  })[];
              }) | null;
              message: string;
            };
          };
        };
      };
    };
    post: {
      parameters: {
        path: {
          dish_id: number;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            dish_ingredients?: {
                /** Format: int64 */
                ingredient_id: number;
                /** Format: int64 */
                weight: number;
              }[] | null;
            is_finished?: boolean | null;
            name: string;
            /** Format: int64 */
            prep_date?: number | null;
            /** Format: int64 */
            total_weight?: number | null;
          };
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              data?: ([{
                  /** Format: int64 */
                  creation_date: number;
                  /** Format: int64 */
                  id: number;
                  /** Format: int64 */
                  is_finished: number;
                  name?: string | null;
                  /** Format: int64 */
                  prep_date?: number | null;
                  /** Format: int64 */
                  total_weight: number;
                }, {
                    /** Format: int64 */
                    creation_date: number;
                    /** Format: int64 */
                    dish_id: number;
                    /** Format: int64 */
                    ingredient_id: number;
                    /** Format: int64 */
                    weight: number;
                  }[]]) | null;
              message: string;
            };
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          dish_id: number;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              data?: boolean | null;
              message: string;
            };
          };
        };
      };
    };
  };
  "/dish/{dish_id}/delete-warning": {
    get: {
      parameters: {
        path: {
          dish_id: number;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              data?: (({
                  meal_description?: string | null;
                  /** Format: int64 */
                  meal_eat_date?: number | null;
                  /** Format: int64 */
                  weight: number;
                })[]) | null;
              message: string;
            };
          };
        };
      };
    };
  };
  "/dish/{dish_id}/weight/": {
    post: {
      parameters: {
        path: {
          dish_id: number;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            /** Format: int64 */
            total_weight: number;
          };
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              data?: {
                /** Format: int64 */
                total_weight: number;
              } | null;
              message: string;
            };
          };
        };
      };
    };
  };
  "/dish/{dish_id}/ingredient/": {
    post: {
      parameters: {
        path: {
          dish_id: number;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            /** Format: int64 */
            ingredient_id: number;
            /** Format: int64 */
            weight: number;
          };
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              data?: {
                /** Format: int64 */
                creation_date: number;
                /** Format: int64 */
                dish_id: number;
                /** Format: int64 */
                ingredient_id: number;
                /** Format: int64 */
                weight: number;
              } | null;
              message: string;
            };
          };
        };
      };
    };
  };
  "/dish/{dish_id}/ingredient/{ingredient_id}": {
    delete: {
      parameters: {
        path: {
          dish_id: number;
          ingredient_id: number;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              data?: boolean | null;
              message: string;
            };
          };
        };
      };
    };
  };
  "/meal/": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": {
              data?: (({
                  /** Format: int64 */
                  creation_date: number;
                  description?: string | null;
                  /** Format: int64 */
                  duration?: number | null;
                  /** Format: int64 */
                  eat_date?: number | null;
                  /** Format: int64 */
                  id: number;
                })[]) | null;
              message: string;
            };
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": {
            components: ({
                /** Format: int64 */
                dish_id?: number | null;
                /** Format: int64 */
                ingredient_id?: number | null;
                /** Format: int64 */
                weight: number;
              })[];
            description?: string | null;
            /** Format: int64 */
            duration?: number | null;
            /** Format: int64 */
            eat_date?: number | null;
          };
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              data?: ({
                meal: {
                  /** Format: int64 */
                  creation_date: number;
                  description?: string | null;
                  /** Format: int64 */
                  duration?: number | null;
                  /** Format: int64 */
                  eat_date?: number | null;
                  /** Format: int64 */
                  id: number;
                };
                meal_dishes: {
                    /** Format: int64 */
                    creation_date: number;
                    /** Format: int64 */
                    id: number;
                    /** Format: int64 */
                    meal_id: number;
                    /** Format: int64 */
                    weight: number;
                  }[];
                meal_ingredients: {
                    /** Format: int64 */
                    creation_date: number;
                    /** Format: int64 */
                    id: number;
                    /** Format: int64 */
                    meal_id: number;
                    /** Format: int64 */
                    weight: number;
                  }[];
              }) | null;
              message: string;
            };
          };
        };
      };
    };
  };
  "/meal/description/": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": {
              data?: string[] | null;
              message: string;
            };
          };
        };
      };
    };
  };
  "/meal/component/": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": {
              data?: ({
                components: ({
                    component_type: string;
                    /** Format: int64 */
                    id: number;
                    name?: string | null;
                  })[];
              }) | null;
              message: string;
            };
          };
        };
      };
    };
    post: {
      parameters: {
        path: {
          meal_id: number;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            /** Format: int64 */
            component_id: number;
            /** @enum {string} */
            component_type: "Dish" | "Ingredient";
            /** Format: int64 */
            weight: number;
          };
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              data?: {
                /** Format: int64 */
                component_id: number;
                /** Format: int64 */
                creation_date: number;
                /** Format: int64 */
                meal_id: number;
                /** Format: int64 */
                weight: number;
              } | null;
              message: string;
            };
          };
        };
      };
    };
  };
  "/meal/{meal_id}/": {
    get: {
      parameters: {
        path: {
          meal_id: number;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              data?: ({
                dishes: ({
                    /** Format: int64 */
                    id: number;
                    name?: string | null;
                    /** Format: int64 */
                    weight: number;
                  })[];
                ingredients: ({
                    /** Format: int64 */
                    id: number;
                    name?: string | null;
                    /** Format: int64 */
                    weight: number;
                  })[];
                meal: {
                  /** Format: int64 */
                  creation_date: number;
                  description?: string | null;
                  /** Format: int64 */
                  duration?: number | null;
                  /** Format: int64 */
                  eat_date?: number | null;
                  /** Format: int64 */
                  id: number;
                };
              }) | null;
              message: string;
            };
          };
        };
      };
    };
    post: {
      parameters: {
        path: {
          meal_id: number;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            components: ({
                /** Format: int64 */
                dish_id?: number | null;
                /** Format: int64 */
                ingredient_id?: number | null;
                /** Format: int64 */
                weight: number;
              })[];
            description?: string | null;
            /** Format: int64 */
            duration?: number | null;
            /** Format: int64 */
            eat_date?: number | null;
          };
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              data?: ({
                meal: {
                  /** Format: int64 */
                  creation_date: number;
                  description?: string | null;
                  /** Format: int64 */
                  duration?: number | null;
                  /** Format: int64 */
                  eat_date?: number | null;
                  /** Format: int64 */
                  id: number;
                };
                meal_dishes: {
                    /** Format: int64 */
                    creation_date: number;
                    /** Format: int64 */
                    id: number;
                    /** Format: int64 */
                    meal_id: number;
                    /** Format: int64 */
                    weight: number;
                  }[];
                meal_ingredients: {
                    /** Format: int64 */
                    creation_date: number;
                    /** Format: int64 */
                    id: number;
                    /** Format: int64 */
                    meal_id: number;
                    /** Format: int64 */
                    weight: number;
                  }[];
              }) | null;
              message: string;
            };
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          meal_id: number;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              data?: boolean | null;
              message: string;
            };
          };
        };
      };
    };
  };
  "/meal/{meal_id}/dish/": {
    post: {
      parameters: {
        path: {
          meal_id: number;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            /** Format: int64 */
            dish_id: number;
            /** Format: int64 */
            weight: number;
          };
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              data?: {
                /** Format: int64 */
                creation_date: number;
                /** Format: int64 */
                dish_id: number;
                /** Format: int64 */
                meal_id: number;
                /** Format: int64 */
                weight: number;
              } | null;
              message: string;
            };
          };
        };
      };
    };
  };
  "/meal/{meal_id}/dish/{dish_id}": {
    delete: {
      parameters: {
        path: {
          dish_id: number;
          meal_id: number;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              data?: boolean | null;
              message: string;
            };
          };
        };
      };
    };
  };
  "/meal/{meal_id}/ingredient/": {
    post: {
      parameters: {
        path: {
          meal_id: number;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            /** Format: int64 */
            ingredient_id: number;
            /** Format: int64 */
            weight: number;
          };
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              data?: {
                /** Format: int64 */
                creation_date: number;
                /** Format: int64 */
                ingredient_id: number;
                /** Format: int64 */
                meal_id: number;
                /** Format: int64 */
                weight: number;
              } | null;
              message: string;
            };
          };
        };
      };
    };
  };
  "/meal/{meal_id}/ingredient/{ingredient_id}": {
    delete: {
      parameters: {
        path: {
          ingredient_id: number;
          meal_id: number;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              data?: boolean | null;
              message: string;
            };
          };
        };
      };
    };
  };
  "/meal/{meal_id}/eat_date/": {
    post: {
      parameters: {
        path: {
          meal_id: number;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            /** Format: int64 */
            eat_date: number;
          };
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              data?: ({
                meal: {
                  /** Format: int64 */
                  creation_date: number;
                  description?: string | null;
                  /** Format: int64 */
                  duration?: number | null;
                  /** Format: int64 */
                  eat_date?: number | null;
                  /** Format: int64 */
                  id: number;
                };
              }) | null;
              message: string;
            };
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export type components = Record<string, never>;

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
